
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testApi
    #db ?? ?? ?? x? ?? ?? ?? ??? ? ?? ?? ??.
    driver-class-name: org.h2.Driver
    username: sa
    password: 12
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

